from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QApplication

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        app = QApplication.instance()
        screen_geometry = app.primaryScreen().availableGeometry()
        screen_width = screen_geometry.width()
        screen_height = screen_geometry.height()
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(int(screen_width * 0.2), int(screen_height * 0.43))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 10, int(screen_width * 0.2), int(screen_height * 0.05)))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, int(screen_height * 0.06), int(screen_width * 0.04), int(screen_height * 0.02)))
        self.label_2.setObjectName("label_2")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(int(screen_width * 0.05), int(screen_height * 0.06), int(screen_width * 0.15), int(screen_height * 0.02)))
        self.lineEdit.setObjectName("lineEdit")
        self.lineEdit_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_2.setGeometry(QtCore.QRect(int(screen_width * 0.05), int(screen_height * 0.08), int(screen_width * 0.15), int(screen_height * 0.02)))
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(10, int(screen_height * 0.08), int(screen_width * 0.04), int(screen_height * 0.02)))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(10, int(screen_height * 0.1), int(screen_width * 0.04), int(screen_height * 0.02)))
        self.label_4.setObjectName("label_4")
        self.lineEdit_3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_3.setGeometry(QtCore.QRect(int(screen_width * 0.05), int(screen_height * 0.1), int(screen_width * 0.15), int(screen_height * 0.02)))
        self.lineEdit_3.setText("")
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(10, int(screen_height * 0.12), int(screen_width * 0.04), int(screen_height * 0.02)))
        self.label_5.setObjectName("label_5")
        self.lineEdit_4 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_4.setGeometry(QtCore.QRect(int(screen_width * 0.05), int(screen_height * 0.12), int(screen_width * 0.15), int(screen_height * 0.02)))
        self.lineEdit_4.setText("")
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(10, int(screen_height * 0.14), int(screen_width * 0.04), int(screen_height * 0.02)))
        self.label_6.setObjectName("label_6")
        self.lineEdit_5 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit_5.setGeometry(QtCore.QRect(int(screen_width * 0.05), int(screen_height * 0.14), int(screen_width * 0.15), int(screen_height * 0.02)))
        self.lineEdit_5.setText("")
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(10, int(screen_height * 0.16), int(screen_width * 0.04), int(screen_height * 0.02)))
        self.label_7.setObjectName("label_7")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(0, int(screen_height * 0.18), int(screen_width * 0.2), int(screen_height * 0.1)))
        self.textEdit.setObjectName("textEdit")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(10, int(screen_height * 0.37), int(screen_width * 0.06), int(screen_height * 0.03)))
        self.pushButton.setObjectName("pushButton")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(10, int(screen_height * 0.30), int(screen_width * 0.08), int(screen_height * 0.02)))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(int(screen_width * 0.09), int(screen_height * 0.30), int(screen_width * 0.1), int(screen_height * 0.02)))
        self.label_8.setObjectName("label_8")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(10, int(screen_height * 0.32), int(screen_width * 0.08), int(screen_height * 0.02)))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(int(screen_width * 0.09), int(screen_height * 0.32), int(screen_width * 0.1), int(screen_height * 0.02)))
        self.label_9.setObjectName("label_9")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(10, int(screen_height * 0.34), int(screen_width * 0.08), int(screen_height * 0.02)))
        self.pushButton_4.setObjectName("pushButton_4")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(int(screen_width * 0.09), int(screen_height * 0.34), int(screen_width * 0.1), int(screen_height * 0.02)))
        self.label_10.setObjectName("label_10")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 245, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Добавить машину:"))
        self.label_2.setText(_translate("MainWindow", "Марка:"))
        self.label_3.setText(_translate("MainWindow", "Модель:"))
        self.label_4.setText(_translate("MainWindow", "Цена:"))
        self.label_5.setText(_translate("MainWindow", "Пробег:"))
        self.label_6.setText(_translate("MainWindow", "Год:"))
        self.label_7.setText(_translate("MainWindow", "Описание:"))
        self.pushButton.setText(_translate("MainWindow", "Сохранение"))
        self.pushButton_2.setText(_translate("MainWindow", "Добавить фото 1"))
        self.label_8.setText(_translate("MainWindow", "Файл не выбран"))
        self.pushButton_3.setText(_translate("MainWindow", "Добавить фото 2"))
        self.label_9.setText(_translate("MainWindow", "Файл не выбран"))
        self.pushButton_4.setText(_translate("MainWindow", "Добавить фото 3"))
        self.label_10.setText(_translate("MainWindow", "Файл не выбран"))
